// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Create produto', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Create produto', async function() {
    await driver.get("https://beleza-pura.onrender.com/")
    await driver.manage().window().setRect({ width: 736, height: 765 })
    await driver.findElement(By.css(".font-montserrat:nth-child(5)")).click()
    await driver.findElement(By.css(".fixed")).click()
    await driver.findElement(By.id("produto")).click()
    await driver.findElement(By.id("produto")).sendKeys("Selagem")
    await driver.findElement(By.id("qtd")).sendKeys("45")
    await driver.findElement(By.name("preco")).sendKeys("100")
    await driver.findElement(By.name("validade")).sendKeys("2029-11-30")
    await driver.findElement(By.css(".mt-6")).click()
  })
})
