// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Update procedimentos', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Update procedimentos', async function() {
    await driver.get("https://beleza-pura.onrender.com/")
    await driver.manage().window().setRect({ width: 736, height: 765 })
    await driver.findElement(By.css(".font-montserrat:nth-child(2)")).click()
    await driver.findElement(By.css(".grid:nth-child(3) .svg-inline--fa:nth-child(1) > path")).click()
    await driver.findElement(By.css(".grid-cols-2")).click()
    await driver.findElement(By.id("preco")).sendKeys("400")
    await driver.findElement(By.css(".mt-4")).click()
  })
})
