// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Update produto', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Update produto', async function() {
    await driver.get("https://beleza-pura.onrender.com/")
    await driver.manage().window().setRect({ width: 736, height: 765 })
    await driver.findElement(By.css(".font-montserrat:nth-child(5)")).click()
    await driver.findElement(By.css(".grid:nth-child(2) > .col-span-1 .svg-inline--fa:nth-child(1) > path")).click()
    await driver.findElement(By.name("preco")).click()
    await driver.findElement(By.name("preco")).sendKeys("500")
    await driver.findElement(By.id("qtd")).click()
    await driver.findElement(By.id("qtd")).sendKeys("12")
    await driver.findElement(By.css(".mt-6")).click()
  })
})
