// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Create usuario', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Create usuario', async function() {
    await driver.get("https://beleza-pura.onrender.com/")
    await driver.manage().window().setRect({ width: 1454, height: 866 })
    await driver.findElement(By.css(".bg-brandGreen")).click()
    await driver.findElement(By.css(".drop-shadow-lg:nth-child(1)")).click()
    await driver.findElement(By.css(".fixed")).click()
    await driver.findElement(By.name("nome")).sendKeys("Jão pé de feijão")
    await driver.findElement(By.name("cpf")).sendKeys("18901883600")
    await driver.findElement(By.name("celular")).sendKeys("35991891457")
    {
      const dropdown = await driver.findElement(By.name("role"))
      await dropdown.findElement(By.xpath("//option[. = 'Cliente']")).click()
    }
    await driver.findElement(By.name("passwordConfirm")).click()
    await driver.findElement(By.css(".px-10")).click()
    await driver.findElement(By.name("email")).sendKeys("joao@gmail.com")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.css(".max-h-\\[60svh\\]")).click()
    await driver.findElement(By.css(".w-\\[60\\%\\]")).click()
    await driver.findElement(By.name("passwordConfirm")).click()
    await driver.findElement(By.css(".w-\\[60\\%\\]")).click()
  })
})
