// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Delete usuario', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Delete usuario', async function() {
    await driver.get("https://beleza-pura.onrender.com/")
    await driver.manage().window().setRect({ width: 1440, height: 852 })
    await driver.findElement(By.css(".bg-brandGreen")).click()
    await driver.findElement(By.css(".drop-shadow-lg:nth-child(1)")).click()
    await driver.findElement(By.css(".grid:nth-child(5) .svg-inline--fa:nth-child(2) > path")).click()
    await driver.findElement(By.css(".bg-red-800")).click()
  })
})
