// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Create agendamentos', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Create agendamentos', async function() {
    await driver.get("https://beleza-pura.onrender.com/")
    await driver.manage().window().setRect({ width: 737, height: 767 })
    await driver.findElement(By.css(".bg-brandGreen")).click()
    await driver.findElement(By.css(".fixed")).click()
    await driver.findElement(By.name("nome")).click()
    await driver.findElement(By.css(".gap-8")).click()
    await driver.findElement(By.name("nome")).click()
    {
      const dropdown = await driver.findElement(By.name("nome"))
      await dropdown.findElement(By.xpath("//option[. = 'Antônio Ramos dos Reis']")).click()
    }
    await driver.findElement(By.css(".italic")).click()
    await driver.findElement(By.css(".hover\\3A bg-gray-200:nth-child(1)")).click()
    {
      const dropdown = await driver.findElement(By.name("cabelereiro"))
      await dropdown.findElement(By.xpath("//option[. = 'Thiago L. Matos']")).click()
    }
    await driver.findElement(By.css(".react-datepicker__day--021")).click()
    await driver.findElement(By.css(".bg-blue-500:nth-child(7)")).click()
    await driver.findElement(By.css(".w-\\[50\\%\\]")).click()
  })
})
