// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Delete agendamentos', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Delete agendamentos', async function() {
    await driver.get("https://beleza-pura.onrender.com/")
    await driver.manage().window().setRect({ width: 737, height: 767 })
    await driver.findElement(By.css(".bg-brandGreen")).click()
    await driver.findElement(By.css(".grid:nth-child(7) .flex .svg-inline--fa:nth-child(2) > path")).click()
    await driver.findElement(By.css(".bg-red-800")).click()
    await driver.findElement(By.css(".fa-xmark > path")).click()
    await driver.findElement(By.css(".grid:nth-child(7) .flex .svg-inline--fa:nth-child(2) > path")).click()
    await driver.findElement(By.css(".bg-red-800")).click()
    await driver.findElement(By.css(".fa-xmark")).click()
  })
})
