// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Update agendamentos', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Update agendamentos', async function() {
    await driver.get("https://beleza-pura.onrender.com/")
    await driver.manage().window().setRect({ width: 1454, height: 866 })
    await driver.findElement(By.css(".bg-brandGreen")).click()
    await driver.findElement(By.css(".grid:nth-child(6) .flex .svg-inline--fa:nth-child(1) > path")).click()
    await driver.findElement(By.css(".react-datepicker__day--011")).click()
    await driver.findElement(By.css(".bg-blue-500:nth-child(3)")).click()
    await driver.findElement(By.css(".w-\\[50\\%\\]")).click()
  })
})
