// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Create contabilidade', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Create contabilidade', async function() {
    await driver.get("https://beleza-pura.onrender.com/")
    await driver.manage().window().setRect({ width: 1454, height: 866 })
    await driver.findElement(By.css(".bg-brandGreen")).click()
    await driver.findElement(By.css(".font-montserrat:nth-child(3)")).click()
    await driver.findElement(By.css(".fixed")).click()
    await driver.findElement(By.name("descricao")).sendKeys("supermercado")
    await driver.findElement(By.name("valor")).sendKeys("300")
    {
      const dropdown = await driver.findElement(By.name("categoria"))
      await dropdown.findElement(By.xpath("//option[. = 'Outros']")).click()
    }
    await driver.findElement(By.name("formaPagamento")).click()
    await driver.findElement(By.name("formaPagamento")).click()
    await driver.findElement(By.css(".py-2")).click()
  })
})
