// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Read contabilidade', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Read contabilidade', async function() {
    await driver.get("https://beleza-pura.onrender.com/overview/usuarios")
    await driver.manage().window().setRect({ width: 1454, height: 866 })
    await driver.findElement(By.css(".font-montserrat:nth-child(3)")).click()
  })
})
