// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Update contabilidade', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Update contabilidade', async function() {
    await driver.get("https://beleza-pura.onrender.com/")
    await driver.manage().window().setRect({ width: 737, height: 767 })
    await driver.findElement(By.css(".bg-brandGreen")).click()
    await driver.findElement(By.css(".font-montserrat:nth-child(3)")).click()
    await driver.findElement(By.css(".grid:nth-child(2) > .col-span-1 .svg-inline--fa:nth-child(1) > path")).click()
    await driver.findElement(By.name("valor")).click()
    await driver.findElement(By.css(".px-16")).click()
    await driver.findElement(By.name("valor")).sendKeys("500")
    {
      const dropdown = await driver.findElement(By.name("categoria"))
      await dropdown.findElement(By.xpath("//option[. = 'Marketing']")).click()
    }
    await driver.findElement(By.css(".py-2")).click()
  })
})
