// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Update equipamentos', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Update equipamentos', async function() {
    await driver.get("https://beleza-pura.onrender.com/")
    await driver.manage().window().setRect({ width: 1454, height: 866 })
    await driver.findElement(By.css(".bg-brandGreen")).click()
    await driver.findElement(By.css(".font-montserrat:nth-child(5)")).click()
    await driver.findElement(By.css(".grid:nth-child(5) .svg-inline--fa:nth-child(1) > path")).click()
    await driver.findElement(By.css(".justify-between:nth-child(2)")).click()
    await driver.findElement(By.id("marca")).sendKeys("Taiff")
    await driver.findElement(By.css(".flex-row:nth-child(3) > .flex")).click()
    await driver.findElement(By.id("voltagem")).sendKeys("220")
    await driver.findElement(By.css(".my-4")).click()
  })
})
