// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Create procedimentos', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Create procedimentos', async function() {
    await driver.get("https://beleza-pura.onrender.com/")
    await driver.manage().window().setRect({ width: 736, height: 765 })
    await driver.findElement(By.css(".bg-brandGreen")).click()
    await driver.findElement(By.css(".font-montserrat:nth-child(2)")).click()
    await driver.findElement(By.css(".fixed")).click()
    await driver.findElement(By.id("procedimento")).sendKeys("Botox")
    await driver.findElement(By.id("preco")).sendKeys("200")
    await driver.findElement(By.id("hora")).sendKeys("3")
    await driver.findElement(By.css(".rounded-t-lg > .text-sm")).click()
    await driver.findElement(By.css(".rounded-b-lg:nth-child(2)")).click()
    await driver.findElement(By.css(".mt-4")).click()
  })
})
