// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Update produtos', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Update produtos', async function() {
    await driver.get("https://beleza-pura.onrender.com/")
    await driver.manage().window().setRect({ width: 1454, height: 866 })
    await driver.findElement(By.css(".bg-brandGreen")).click()
    await driver.findElement(By.css(".font-montserrat:nth-child(4)")).click()
    await driver.findElement(By.css(".grid:nth-child(1) .svg-inline--fa:nth-child(1) > path")).click()
    await driver.findElement(By.id("pesoLiquido")).sendKeys("300ml")
    await driver.findElement(By.css(".mt-6")).click()
  })
})
